**CHURN PREDICTION**

In [ ]:
#To support pandas profiling
pip install pandas==0.25 

     |████████████████████████████████| 10.5MB 2.6MB/s 
ERROR: google-colab 1.0.0 has requirement pandas~=1.0.0; python_version >= "3.0", but you'll have pandas 0.25.0 which is incompatible.
  Found existing installation: pandas 1.0.5
    Uninstalling pandas-1.0.5:
      Successfully uninstalled pandas-1.0.5


**LIBRARIES TO BE INCLUDED**

In [ ]:
import numpy as np
import matplotlib.pyplot as plt


In [ ]:
from scipy import stats
import pandas as pd
import sys

# use seaborn plotting defaults
import seaborn as se; se.set()

**UNDERSTANDING THE DATASET**

In [ ]:
datasets = pd.read_csv('Churn.csv')

In [ ]:
datasets.head()

customerID  gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
0  7590-VHVEG  Female              0  ...          29.85        29.85     No
1  5575-GNVDE    Male              0  ...          56.95       1889.5     No
2  3668-QPYBK    Male              0  ...          53.85       108.15    Yes
3  7795-CFOCW    Male              0  ...          42.30      1840.75     No
4  9237-HQITU  Female              0  ...          70.70       151.65    Yes

[5 rows x 21 columns]

**PROFILING FOR FEATURE EXTRACTION (CORRELATION THROUGH PEARSON FILTERING)**

In [ ]:
import pandas_profiling
pandas_profiling.ProfileReport(datasets)

/usr/local/lib/python3.6/dist-packages/pandas_profiling/describe.py:392: FutureWarning: The join_axes-keyword is deprecated. Use .reindex or .reindex_like on the result to achieve the same functionality.
  variable_stats = pd.concat(ldesc, join_axes=pd.Index([names]), axis=1)


**DATA PRE PROCESSING**

In [ ]:
datasets["MonthlyCharges"] = pd.to_numeric(datasets["MonthlyCharges"], downcast="float")

In [ ]:
datasets.head()

customerID  gender  SeniorCitizen  ... MonthlyCharges TotalCharges  Churn
0  7590-VHVEG  Female              0  ...      29.850000        29.85     No
1  5575-GNVDE    Male              0  ...      56.950001       1889.5     No
2  3668-QPYBK    Male              0  ...      53.849998       108.15    Yes
3  7795-CFOCW    Male              0  ...      42.299999      1840.75     No
4  9237-HQITU  Female              0  ...      70.699997       151.65    Yes

[5 rows x 21 columns]

In [ ]:
datasets=datasets.drop(['customerID'], axis=1)

**TRAINING AND TESTING SET**

In [ ]:
Y=datasets.iloc[:,-1].values

In [ ]:
X=datasets.iloc[:,[1,4,17]]

In [ ]:
X

SeniorCitizen  tenure  MonthlyCharges
0                 0       1       29.850000
1                 0      34       56.950001
2                 0       2       53.849998
3                 0      45       42.299999
4                 0       2       70.699997
...             ...     ...             ...
7038              0      24       84.800003
7039              0      72      103.199997
7040              0      11       29.600000
7041              1       4       74.400002
7042              0      66      105.650002

[7043 rows x 3 columns]

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.30)

**LOGISTIC REGRESSION**

In [ ]:
from sklearn.linear_model import LogisticRegression

logreg = LogisticRegression(fit_intercept = False, C = 1e12, solver 
= 'liblinear')

logreg.fit(X_train, Y_train)

LogisticRegression(C=1000000000000.0, class_weight=None, dual=False,
                   fit_intercept=False, intercept_scaling=1, l1_ratio=None,
                   max_iter=100, multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='liblinear', tol=0.0001, verbose=0,
                   warm_start=False)

In [ ]:
y_hat_train = logreg.predict(X_train)
y_hat_test = logreg.predict(X_test)

**PERFORMANCE METRICS OF LOGISTIC REGRESSION**

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result = confusion_matrix(Y_test, y_hat_test)
print("Confusion Matrix:")
print(result)
result1 = classification_report(Y_test, y_hat_test)
print("Classification Report:",)
print (result1)
result2 = accuracy_score(Y_test,y_hat_test)
print("Accuracy:",result2)

Confusion Matrix:
[[1265  296]
 [ 219  333]]
Classification Report:
              precision    recall  f1-score   support

          No       0.85      0.81      0.83      1561
         Yes       0.53      0.60      0.56       552

    accuracy                           0.76      2113
   macro avg       0.69      0.71      0.70      2113
weighted avg       0.77      0.76      0.76      2113

Accuracy: 0.7562707051585423


**RANDOM FOREST CLASSIFIER**

In [ ]:
from sklearn.ensemble import RandomForestClassifier
random_classifier= RandomForestClassifier()
random_classifier.fit(X_train,Y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [ ]:
y_pred= random_classifier.predict(X_test)

**PERFORMANCE OF RANDOM FOREST CLASSIFIER**

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result = confusion_matrix(Y_test, y_hat_test)
print("Confusion Matrix:")
print(result)
result1 = classification_report(Y_test, y_hat_test)
print("Classification Report:",)
print (result1)
result2 = accuracy_score(Y_test,y_hat_test)
print("Accuracy:",result2)

Confusion Matrix:
[[1066  464]
 [ 418  165]]
Classification Report:
              precision    recall  f1-score   support

          No       0.72      0.70      0.71      1530
         Yes       0.26      0.28      0.27       583

    accuracy                           0.58      2113
   macro avg       0.49      0.49      0.49      2113
weighted avg       0.59      0.58      0.59      2113

Accuracy: 0.5825840037860861


**SVM**

In [ ]:
from sklearn.svm import SVC
svm_classifier= SVC(probability=True)
svm_classifier.fit(X_train,Y_train)

SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=True, random_state=None, shrinking=True, tol=0.001,
    verbose=False)

In [ ]:
y_pred_svm= svm_classifier.predict(X_test)

**PERFORMANCE METRICS OF SVM**

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result = confusion_matrix(Y_test, y_hat_test)
print("Confusion Matrix:")
print(result)
result1 = classification_report(Y_test, y_hat_test)
print("Classification Report:",)
print (result1)
result2 = accuracy_score(Y_test,y_hat_test)
print("Accuracy:",result2)

Confusion Matrix:
[[1099  450]
 [ 385  179]]
Classification Report:
              precision    recall  f1-score   support

          No       0.74      0.71      0.72      1549
         Yes       0.28      0.32      0.30       564

    accuracy                           0.60      2113
   macro avg       0.51      0.51      0.51      2113
weighted avg       0.62      0.60      0.61      2113

Accuracy: 0.604827259820161
